services:
  db:
    image: mongo:4.4
  app:
    build: .
    user: root  # Forzamos ejecución como root
    # Ya no necesitamos el apk add aquí, solo el certificado y el inicio
    command: /bin/sh -c "mkdir -p artifacts/cert && openssl req -x509 -newkey rsa:4096 -keyout artifacts/cert/server.key -out artifacts/cert/server.crt -days 365 -nodes -subj '/CN=localhost' && PORT=4001 npm start"
    ports:
      - "4001:4001"
    depends_on:
      - db
    environment:
      - PORT=4001
      - MONGODB_URI=mongodb://db:27017/nodegoat
    tty: true
    stdin_open: true
