services:
  db:
    image: mongo:4.4
  app:
    build: .
    command: npm start
    ports:
      - "4001:4000"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/nodegoat
    tty: true
    stdin_open: true
